# Generated by Django 6.0.3 on 2026-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_folder_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processing_status',
            field=models.CharField(default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='resized_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resized/'),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
    ]
