# Generated by Django 6.0.3 on 2026-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_file_processing_status_file_resized_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/originals/'),
        ),
    ]
